### ISSUE TITLE
🔮[RFC #0000]: I hope openim supports windows, mac, linux

### ISSUE THREAD

**Issue by yearspan** [openimsdk/open-im-sdk-flutter#143] opened 2024-02-28 07:22 UTC
希望openim flutter版支持windows、mac、linux，添加相应的本地库目录，用于开发flutter桌面应用程序

**Comment by std-s** [comment] 2024-08-12 01:42
Duplicate of #137

**Closed by std-s** 2024-08-12 01:42 UTC
Labels: enhancement
